#!/bin/bash
#
# Create or update a stack.
#
# Before running this script update the 'user-data' and/or 'stack.json' files in this directory as appropriate.
#
# This script takes 2 parameters, in this order:
#
#   ./stack <create|update> <stack-name>
#
# Once a stack has been updated, you may have to manually terminate/restart
# all instances in order for things like new instance user-data to actually
# be used.
#

# encode the 'user-data' file into a BASE64 string (use Perl since the Linux(GNU)/OSX(BSD) 'base64' utils are different
BASE64_USERDATA=$(perl -MMIME::Base64 -0777ne 'print encode_base64($_, "")' user-data)
if [[ ${#BASE64_USERDATA} -gt 8192 ]]; then
  echo "Base64 encoded user-data is ${#BASE64_USERDATA} characters - max is 8192!"
  exit 1
fi
BASE64_USERDATA1=${BASE64_USERDATA:0:4096}
BASE64_USERDATA2=${BASE64_USERDATA:4096:8192}
echo "Length of the BASE64 encoded user-data is ${#BASE64_USERDATA1} and ${#BASE64_USERDATA2} (max size allowed for either is 4096.)"

# run the AWS CloudFormation command to take action
aws cloudformation $1-stack \
    --profile geoglam-nm \
    --region ap-southeast-2 \
    --stack-name "$2" \
    --template-body file://stack.json \
    --capabilities CAPABILITY_IAM \
    --parameters \
      ParameterKey=ImageId,ParameterValue='ami-2a644649' \
      ParameterKey=InstanceType,ParameterValue='t2.medium' \
      ParameterKey=MaxSize,ParameterValue='2' \
      ParameterKey=MinSize,ParameterValue='1' \
      ParameterKey=UserDataBase64a,ParameterValue="${BASE64_USERDATA1}" \
      ParameterKey=UserDataBase64b,ParameterValue="${BASE64_USERDATA2}" \
      ParameterKey=WebServerPort,ParameterValue='80' \
      ParameterKey=StartupGracePeriod,ParameterValue='1200' \
      ParameterKey=HealthCheck,ParameterValue='HTTP:80/' \
      ParameterKey=KeyName,ParameterValue='rdengate'



